create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 3 and 1500),
  mood text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 180),
  created_at timestamptz not null default now()
);

create table if not exists public.glows (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 2 and 160),
  created_at timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  artist text not null default '',
  platform text not null,
  url text not null,
  note text not null check (char_length(note) between 2 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  created_at timestamptz not null default now()
);

create index if not exists comments_post_id_idx on public.comments(post_id);
create index if not exists page_views_created_at_idx on public.page_views(created_at);

alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.glows enable row level security;
alter table public.songs enable row level security;
alter table public.page_views enable row level security;
